apiVersion: ec2.aws.crossplane.io/v1beta1
kind: VPC
metadata:
  name: myeks-vpc
spec:
  forProvider:
    region: us-west-1
    cidrBlock: 10.0.0.0/16
    enableDnsSupport: true
    enableDnsHostNames: true
    instanceTenancy: default
    tags:
      - key: Name
        value: myeks-vpc
  providerConfigRef:
    name: default