apiVersion: ec2.aws.crossplane.io/v1beta1
kind: Subnet
metadata:
  name: myeks-vpc-subnet1
spec:
  forProvider:
    region: us-west-1
    availabilityZone: us-west-1a
    cidrBlock: 10.0.1.0/24
    vpcIdRef:
      name: myeks-vpc
    mapPublicIPOnLaunch: true
    tags:
      - key: Name
        value: myeks-vpc-subnet1
  providerConfigRef:
    name: default
---
apiVersion: ec2.aws.crossplane.io/v1beta1
kind: Subnet
metadata:
  name: myeks-vpc-subnet2
spec:
  forProvider:
    region: us-west-1
    availabilityZone: us-west-1b
    cidrBlock: 10.0.10.0/24
    vpcIdRef:
      name: myeks-vpc
    mapPublicIPOnLaunch: true
    tags:
      - key: Name
        value: myeks-vpc-subnet2
  providerConfigRef:
    name: default    